---
name: analytics
full_name: Analytics Guild
type: docs
owner_type: "working-group"
status: active
testable: false
description: >
  We intend to integrate website analytics into all 18F projects.
stage: live
links:
- url: https://github.com/18F/g-analytics
  text: 18F Analytics Guild project site
- url: https://github.com/18F/analytics-standards
  text: 18F Analytics Standards
- url: https://docs.google.com/document/u/1/d/1ntHEPBUDBR4_S3z0wHiMeplwT_q3RMLqI-hsJN_u2SE/edit?usp=drive_web
  text: 18F Analytics Guild OKRs 
team:
- github: gbinal
  role: lead
- github: ramirezg
- github: juliawinn
- github: catherinedevlin
