---
name: analytics
full_name: Analytics Guild
type: docs
owner_type: "working-group"
status: active
testable: false
description: >
  We intend to integrate website analytics into all 18F projects.
stage: live
links:
- url: https://github.com/18F/analytics
  text: 18F Analytics Guild project site
- url: https://github.com/18F/analytics-standards
  text: 18F Analytics Standards
team:
- github: gbinal
  role: lead
- github: jackiekazil
  role: lead
- github: ramirezg
